Fix handler for preliquidation contract creation events in PreLiquidationFactory.ts
Indexer fails because the event handler is trying to write to a non-existent table `preLiquidation` not defined in ponder.schema.ts
The correct table name, as per the schema file, is `preLiquidationContract`

Error message from indexer: 
`4:11:50 PM ERROR indexing   Error while processing 'PreLiquidationFactory:CreatePreLiquidation' event in 'Base' block 28411944

TypeError: Cannot read properties of undefined (reading `'Symbol(drizzle:Name)')
    at getTableName (file:///home/ubuntu/morpho-liquidator/node_modules/.pnpm/drizzle-orm@0.41.0_@electric-sql+pglite@0.2.13_@opentelemetry+api@1.9.0_kysely@0.26.3_pg@8.14.1/node_modules/src/table.ts:144:9)
    at Object.then (file:///home/ubuntu/morpho-liquidator/node_modules/.pnpm/ponder@0.11.3_@opentelemetry+api@1.9.0_@types+node@20.17.28_hono@4.7.5_typescript@5.8.2_viem@_cawx7c7v6h3zjv7zbe3qu2sfhi/node_modules/ponder/src/indexing-store/historical.ts:184:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)`

Example tx hash that triggers the error when it gets indexed:  https://basescan.org/tx/0x859443460df4cf3c077830ddaac9618b30ce7a9335fff190cd47c6ce6cef6acd

Signed-off-by: colin-rx <78317368+colin-rx@users.noreply.github.com>